# Generated by Django 4.2.5 on 2023-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_numero_medecin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testme',
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Non binaire', 'Non binaire')], max_length=11, verbose_name='Sexe'),
        ),
    ]
